name: Artifact Cleanup

on:
  schedule:
    # Run every Sunday at midnight UTC
    - cron: '0 0 * * 0'

  workflow_dispatch:

permissions:
  actions: write

jobs:
  cleanup:
    name: Delete Old Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '7 days'
          skip-tags: true
          skip-recent: 10
